### ISSUE TITLE
Fix `astral-sh/setup-uv@v6` config

### ISSUE THREAD

**Issue by joshuadavidthomas** [joshuadavidthomas/django-language-server#126]
> Unexpected input(s) 'pyproject-file', valid inputs are ['version', 'python-version', 'activate-environment', 'working-directory', 'checksum', 'github-token', 'enable-cache', 'cache-dependency-glob', 'cache-suffix', 'cache-local-path', 'prune-cache', 'ignore-nothing-to-cache', 'ignore-empty-workdir', 'tool-dir', 'tool-bin-dir']

Must have been removed in the latest version.

```
Run astral-sh/setup-uv@v6
  with:
    enable-cache: true
    pyproject-file: pyproject.toml
    activate-environment: false
    working-directory: /home/runner/work/django-language-server/django-language-server
    github-token: ***
    cache-dependency-glob: **/*requirements*.txt
  **/*requirements*.in
  **/*constraints*.txt
  **/*constraints*.in
  **/pyproject.toml
  **/uv.lock
  
    prune-cache: true
    ignore-nothing-to-cache: false
    ignore-empty-workdir: false
  env:
    CARGO_TERM_COLOR: always
    FORCE_COLOR: 1
    PYTHONUNBUFFERED: 1
```
