### ISSUE TITLE
Create "TagSpecs" templatetag specification

### ISSUE THREAD

**Issue by joshuadavidthomas** [joshuadavidthomas/django-language-server#65]
Django template tags don't follow consistent patterns (intermediate tags like `else`, arbitrary closing tags, variable scope). Need a way to define their behavior for LSP features.

### Proposed Solution
TOML-based spec files:

```toml
[django.template.defaulttags]
if = {
    type = "block",
    closing = "endif",
    intermediates = ["else", "elif"],
    valid_args = ["*"]
}
```

### Questions
- What's the minimum parsing needed for LSP features vs full AST?
- How handle unknown tags without specs?
- Performance impact of external spec lookups?
- Default behavior for third-party tags?

### Key Points
- Define tag type, closing tags, intermediates, variables, and arg patterns
- Extensible via pyproject.toml
- Focus on LSP features over full AST parsing
